---
- name: sample test
  hosts: localhost
  connection: local
  
  vars_files:
    - group_vars/main.yaml
  vars:
    - products: [asa, gd]

  tasks:

    - command:
        echo {{item}} {{ color }}
      with_sequence: count=2
      vars:
        - color: brown
      register: sequence
      tags:
        - sequence_count

    - command:
        hostname -f
      register: hostname
      tags:
        - simple

    - command:
        echo {{item}}
      register: random_choice
      with_random_choice:
        - "something"
        - "more"
        - "sdsd"
      tags:
        - random_choice

    - command:
        cat /etc/redhat-release
      register: result
      until: result.stdout.find("24") != -1
      retries: 5
      delay: 1
      tags:
        - until_find

    - command:
        echo {{item}}
      with_indexed_items: "{{ products }}"
      register: indexed_items
      tags:
        - indexed_items

    - name: Debug task
      debug:
        msg: Hello world!
      tags:
        - debug

    - name: Template task
      template:
        src: templates/test.j2
        dest: /tmp/test.txt
      tags:
        - template
