#!/bin/bash

ansible-playbook   -vv test_playbook_local.yaml
# ansible-playbook -i hosts.ini -v sample_playbook.yaml
#ansible-playbook -i hosts.ini -v sample_playbook.yaml --extra-vars "sample=true"

