---
- name: sample
  hosts: test-host
  #vars:
  #  - date: 1
  tasks:
    - command: >
        echo {{ date }}
      when: date != 1
      tags:
        - one

    - command: >
        date
      when: date == 1
      tags:
        - two

###################################
# - name: test
#   hosts: test-host
#   #connection: local
  
#   vars_files:
#     - group_vars/main.yaml
#   vars:
#     - products: [asa, gd]
#     - file_present: false
    
#   tasks:

#     - stat: path=/tmp/alpha.txt
#       register: simple_task
#       tags:
#         - simple

#     - debug:
#         msg: "File exists: {{ file_present }}"
#       when: simple_task.stat.exists == true
#       tags:
#         - check_path

#     - file: path=/tmp/alpha.txt state=touch
#       when: simple_task.stat.exists != true
#       register: simple_pre
#       tags:
#         - simple_pre

#     - copy: >
#             content="lacosa" dest="/tmp/alpha.txt"
#       when: simple_pre.changed or simple_task.stat.exists == true
#       tags:
#         - add_content

#     - command: >
#         echo {{item}} {{ color }}
#       with_sequence: count=2
#       vars:
#         - color: brown
#       register: sequence
#       tags:
#         - sequence_count

#     - command: >
#             cat "/tmp/alpha.txt"
#       when: simple_task.stat.exists == true

#     - command: >
#         echo {{item}}
#       register: random_choice
#       with_random_choice:
#         - "something"
#         - "more"
#         - "sdsd"
#       tags:
#         - random_choice

#     - command:
#         cat /etc/redhat-release
#       register: result
#       until: result.stdout.find("24") != -1
#       retries: 5
#       delay: 1
#       tags:
#         - until_find

#     - command: >
#         echo {{item}}
#       with_indexed_items: "{{ products }}"
#       register: indexed_items
#       tags:
#         - indexed_items

#     - name: Debug task
#       debug:
#         msg: Hello world!
#       tags:
#         - debug

#     - name: Template task
#       template:
#         src: templates/test.j2
#         dest: /tmp/test.txt
#       tags:
#         - template

###############################

# - hosts: docker-hosts
#   remote_user: root
#   vars_files:
#     - group_vars/main.yaml
#   roles:
#     - { role: backup,
#       when: sample == true }
  
# - name: sample test
#   hosts: capsules
#   remote_user: root
#   vars_files:
#     - group_vars/main.yaml

#   tasks:
#     - shell: ls /root/
#       register: data
#       when: sample == true      

#     - shell: ls /etc/
#       register: tota
#       when: data.changed
