---
- name: sample test
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/main.yaml

  vars:
    - products: [asa, gd]
    
  tasks:
  
    - command:
        echo {{item}}
      with_sequence: count=2
      register: sequence

    - command:
        hostname -f
      register: hostname

    - command:
        echo {{item}}
      register: random_choice
      with_random_choice:
        - "something"
        - "more"
        - "sdsd"

    - command:
        cat /etc/redhat-release
      register: result
      until: result.stdout.find("24") != -1
      retries: 5
      delay: 1

    - command:
        echo {{item}}
      with_indexed_items: "{{ products }}"
      register: indexed_items
