#!/usr/bin/python
# -*- coding: utf-8 -*- 

"""
Converts all the video files present in current directory.
Depends on 'sc' command, which could be installed by copying 
'sc' script, present in this repo, to /usr/sbin/
"""

from subprocess import call
from os import listdir, mkdir
from glob import glob

#files = [x for x in listdir('.') if ('.' in x)]
def convert(files, ext):
    if files:
        print "Converting %s type files" % (ext)
        for entry in files:
            name = entry.rstrip(ext) + '.mp3'
            cmd = ['sc', entry, name]
            try:
                call(cmd)
            except:
                quit("sound converter script 'sc' not installed!")
    else:
        print "%s type files not present" % (ext)

extensions = ['.webm', '.mp4', '.avi']

for x in extensions:
    files = glob('*'+x)
    if files:
        convert(files, x)

# try:
#     mkdir('converted')
#     call(['mv','*.mp3','converted/'])
# except:
#     call(['mv','*.mp3','converted/'])
