---
#  - shell: ls /root/
#    register: data

  - shell: echo "{{ item }}"
    with_sequence: "count={{ NUMCV_2 }}"

  - shell: echo "{{ item }}"
    with_items: "{{ products }}"
    # failed_when: "token_dep|failed"
  
# - debug:
#     var: token_dep
#     verbosity: 3
    
...
