#!/bin/sh

# <username>/<repository> from Docker Web Hub
docker search /learn/tutorial
docker pull /learn/tutorial

# run sample command in container
docker run /learn/tutorial echo "Hello Arco!"

# install ping 
docker run /learn/tutorial apt-get install -y ping

# find the ID of the container you just created by installing ping
docker ps -l 

# use that container ID to save changes
docker commit <container id> arcolife/ping

# run ping
docker run /arcolife/ping ping google.com

# list all running containers
docker ps

# list all containers used
docker ps -a

# list last used container
docker ps -l

# push image created to registry
docker push arcolife/ping

# get ip address etc.. 
docker inspect <container id>

# run docker and keep it running
docker run -d <container name>

# get inside the container bash
docker  run -it  -p :80 <container name> bash


## compose

docker-compose exec <service name> <command line>
